global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: otel
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: 0
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0

remote_read:
  - url: http://otel:8888/metrics
    remote_timeout: "1m"
    read_recent: false
    follow_redirects: true
  - url: http://otel:8889/metrics
    remote_timeout: "1m"
    read_recent: false
    follow_redirects: true
